function [ke,pe,te] = getEnergy(q,pdw,foot_anchor)
    th1 = q(1); th2 = q(2);
    th1d = q(3); th2d = q(4);
    gamma = pdw.gamma;
    l1 = pdw.l1; l2 = pdw.l2;
    m1 = pdw.m1; m2 = pdw.m2; mh = pdw.mh;
    x = foot_anchor(1); y = foot_anchor(2);
    xd = 0; yd = 0;
    ke = (m2*(xd - th1d*(l1*(cos(gamma)*cos(th1) + sin(gamma)*sin(th1)) - (l2*(cos(th2)*(cos(gamma)*cos(th1) + sin(gamma)*sin(th1)) - sin(th2)*(cos(gamma)*sin(th1) - cos(th1)*sin(gamma))))/2) + (l2*th2d*(cos(th2)*(cos(gamma)*cos(th1) + sin(gamma)*sin(th1)) - sin(th2)*(cos(gamma)*sin(th1) - cos(th1)*sin(gamma))))/2)^2)/2 + (m2*(yd - th1d*(l1*(cos(gamma)*sin(th1) - cos(th1)*sin(gamma)) - (l2*(cos(th2)*(cos(gamma)*sin(th1) - cos(th1)*sin(gamma)) + sin(th2)*(cos(gamma)*cos(th1) + sin(gamma)*sin(th1))))/2) + (l2*th2d*(cos(th2)*(cos(gamma)*sin(th1) - cos(th1)*sin(gamma)) + sin(th2)*(cos(gamma)*cos(th1) + sin(gamma)*sin(th1))))/2)^2)/2 + (m1*(xd - (l1*th1d*(cos(gamma)*cos(th1) + sin(gamma)*sin(th1)))/2)^2)/2 + (mh*(xd - l1*th1d*(cos(gamma)*cos(th1) + sin(gamma)*sin(th1)))^2)/2 + (m1*(yd - (l1*th1d*(cos(gamma)*sin(th1) - cos(th1)*sin(gamma)))/2)^2)/2 + (mh*(yd - l1*th1d*(cos(gamma)*sin(th1) - cos(th1)*sin(gamma)))^2)/2 + (l2^2*m2*(th1d + th2d)^2)/24 + (l1^2*m1*th1d^2)/24;
    pe = (981*m2*(y + l1*(cos(gamma)*cos(th1) + sin(gamma)*sin(th1)) - (l2*(cos(th2)*(cos(gamma)*cos(th1) + sin(gamma)*sin(th1)) - sin(th2)*(cos(gamma)*sin(th1) - cos(th1)*sin(gamma))))/2))/100 + (981*m1*(y + (l1*(cos(gamma)*cos(th1) + sin(gamma)*sin(th1)))/2))/100 + (981*mh*(y + l1*(cos(gamma)*cos(th1) + sin(gamma)*sin(th1))))/100;
    te = (m2*(xd - th1d*(l1*(cos(gamma)*cos(th1) + sin(gamma)*sin(th1)) - (l2*(cos(th2)*(cos(gamma)*cos(th1) + sin(gamma)*sin(th1)) - sin(th2)*(cos(gamma)*sin(th1) - cos(th1)*sin(gamma))))/2) + (l2*th2d*(cos(th2)*(cos(gamma)*cos(th1) + sin(gamma)*sin(th1)) - sin(th2)*(cos(gamma)*sin(th1) - cos(th1)*sin(gamma))))/2)^2)/2 + (m2*(yd - th1d*(l1*(cos(gamma)*sin(th1) - cos(th1)*sin(gamma)) - (l2*(cos(th2)*(cos(gamma)*sin(th1) - cos(th1)*sin(gamma)) + sin(th2)*(cos(gamma)*cos(th1) + sin(gamma)*sin(th1))))/2) + (l2*th2d*(cos(th2)*(cos(gamma)*sin(th1) - cos(th1)*sin(gamma)) + sin(th2)*(cos(gamma)*cos(th1) + sin(gamma)*sin(th1))))/2)^2)/2 + (981*m2*(y + l1*(cos(gamma)*cos(th1) + sin(gamma)*sin(th1)) - (l2*(cos(th2)*(cos(gamma)*cos(th1) + sin(gamma)*sin(th1)) - sin(th2)*(cos(gamma)*sin(th1) - cos(th1)*sin(gamma))))/2))/100 + (m1*(xd - (l1*th1d*(cos(gamma)*cos(th1) + sin(gamma)*sin(th1)))/2)^2)/2 + (mh*(xd - l1*th1d*(cos(gamma)*cos(th1) + sin(gamma)*sin(th1)))^2)/2 + (m1*(yd - (l1*th1d*(cos(gamma)*sin(th1) - cos(th1)*sin(gamma)))/2)^2)/2 + (mh*(yd - l1*th1d*(cos(gamma)*sin(th1) - cos(th1)*sin(gamma)))^2)/2 + (981*m1*(y + (l1*(cos(gamma)*cos(th1) + sin(gamma)*sin(th1)))/2))/100 + (981*mh*(y + l1*(cos(gamma)*cos(th1) + sin(gamma)*sin(th1))))/100 + (l2^2*m2*(th1d + th2d)^2)/24 + (l1^2*m1*th1d^2)/24;
end

